on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: run-with-brew

jobs:
  run1:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew install gdal

      - name: Install package for scan
        run: Rscript -e 'install.packages(c("terra"), repos = "https://cran.rstudio.com/")'

      - name: Get data
        run: Rscript -e 'source("data-raw/DATASET.R", echo = TRUE)'

